import { Dimensions, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#f4f5f7' },
  header: {
    height: 60,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
  },
  headerBackButton: {
    width: 50,
    height: 40,
    justifyContent: 'center',
  },
  headerBackButtonText: { fontSize: 26, color: '#222222' },
  title: { fontSize: 18, fontWeight: '700', color: '#111111' },
  titleButton: { flex: 1, minHeight: 48, justifyContent: 'center' },
  create: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#202b3d',
  },
  createGlyph: { fontSize: 25, lineHeight: 29, color: '#fff' },
  filters: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 11,
    gap: 7,
    backgroundColor: '#f4f5f7',
  },
  chip: {
    paddingHorizontal: 13,
    paddingVertical: 7,
    borderRadius: 18,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e7e9ed',
  },
  chipActive: { backgroundColor: '#202b3d', borderColor: '#202b3d' },
  chipText: { fontSize: 12, fontWeight: '600', color: '#667085' },
  chipTextActive: { color: '#fff' },
  communityNav: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 8,
    gap: 8,
    backgroundColor: '#fff',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e6e8eb',
  },
  communityNavItem: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 15,
  },
  communityNavItemActive: { backgroundColor: '#202b3d' },
  communityNavText: { color: '#667085', fontSize: 12, fontWeight: '600' },
  communityNavTextActive: { color: '#fff' },
  myPostsButton: {
    marginLeft: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: '#e8eef6',
  },
  myPostsGlyph: { fontSize: 13, color: '#355b92' },
  myPostsButtonText: { fontSize: 11, fontWeight: '700', color: '#355b92' },
  myPostsBar: {
    minHeight: 72,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e6e8eb',
  },
  myAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#90a9d8',
  },
  myAvatarText: { fontSize: 15, fontWeight: '700', color: '#fff' },
  myPostsInfo: {
    flex: 1,
    marginLeft: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  myPostsStat: { alignItems: 'center', minWidth: 56 },
  myPostsTitle: { fontSize: 15, fontWeight: '700', color: '#20242d' },
  myPostsCaption: { fontSize: 10, color: '#9299a5', marginTop: 3 },
  backToFeed: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#e3e6eb',
    borderRadius: 16,
  },
  backToFeedText: { fontSize: 11, color: '#596579', fontWeight: '600' },
  list: { paddingBottom: 22 },
  gridList: { paddingBottom: 20 },
  gridRow: { gap: 2, marginBottom: 2 },
  gridTile: {
    width: (Dimensions.get('window').width - 4) / 3,
    flexGrow: 0,
    flexShrink: 0,
    aspectRatio: 1,
    backgroundColor: '#e7e9ed',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridImage: { width: '100%', height: '100%' },
  gridEmpty: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e8edf4',
  },
  gridEmptyGlyph: { color: '#6f7d92', fontSize: 28 },
  gridMultipleBadge: {
    position: 'absolute',
    top: 5,
    right: 6,
  },
  gridBadgeText: {
    color: '#fff',
    fontSize: 18,
    textShadowColor: '#222',
    textShadowRadius: 4,
  },
  gridCaption: {
    position: 'absolute',
    left: 7,
    right: 7,
    bottom: 7,
    padding: 5,
    borderRadius: 5,
    backgroundColor: 'rgba(20,25,35,0.65)',
    color: '#fff',
    fontSize: 10,
  },
  postCard: {
    backgroundColor: '#fff',
    marginBottom: 9,
    paddingTop: 13,
    paddingBottom: 14,
  },
  postHeader: {
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  postAuthorPressable: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  avatar: {
    width: 39,
    height: 39,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#90a9d8',
  },
  avatarText: { fontSize: 15, fontWeight: '700', color: '#fff' },
  avatarImage: { width: '100%', height: '100%', borderRadius: 24 },
  author: { flex: 1, marginLeft: 9 },
  authorName: { fontSize: 13, fontWeight: '700', color: '#20242d' },
  meta: { fontSize: 10, color: '#9299a5', marginTop: 3 },
  more: { fontSize: 23, color: '#596171', paddingHorizontal: 5 },
  caption: {
    fontSize: 13,
    lineHeight: 20,
    color: '#343a46',
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  mediaFrame: {
    width: Dimensions.get('window').width,
    aspectRatio: 0.98,
    backgroundColor: '#e7e9ed',
    overflow: 'hidden',
  },
  mediaGalleryContainer: { position: 'relative' },
  mediaGallery: { width: '100%' },
  image: { width: '100%', height: '100%' },
  mediaCountBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    borderRadius: 12,
    paddingHorizontal: 9,
    paddingVertical: 5,
    backgroundColor: 'rgba(20,25,35,0.62)',
  },
  videoPreview: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#283449',
  },
  videoPlayGlyph: { fontSize: 40, color: '#fff' },
  videoPreviewText: { fontSize: 13, color: '#fff', marginTop: 8 },
  videoBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    borderRadius: 12,
    paddingHorizontal: 9,
    paddingVertical: 5,
    backgroundColor: 'rgba(20,25,35,0.62)',
  },
  videoText: { fontSize: 10, fontWeight: '600', color: '#fff' },
  actions: {
    paddingHorizontal: 15,
    paddingTop: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  actionGroup: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  actionGlyph: { fontSize: 23, color: '#293140' },
  liked: { color: '#e34e67' },
  count: { fontSize: 12, color: '#4a5260', marginRight: 9 },
  commentBubble: {
    width: 17,
    height: 13,
    borderWidth: 1.7,
    borderColor: '#293140',
    borderRadius: 4,
    backgroundColor: '#fff',
  },
  commentBubbleTail: {
    position: 'absolute',
    left: 2,
    bottom: -3,
    width: 5,
    height: 5,
    borderLeftWidth: 1.5,
    borderBottomWidth: 1.5,
    borderColor: '#293140',
    backgroundColor: '#fff',
    transform: [{ rotate: '-45deg' }],
  },
  commentAction: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  saveAction: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookmarkIcon: { width: 20, height: 20 },
  toast: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 34,
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 8,
    backgroundColor: 'rgba(32, 36, 45, 0.92)',
    zIndex: 10,
    elevation: 6,
  },
  toastText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  commentToast: { bottom: 88 },
  savedListBar: {
    height: 58,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e6e8eb',
  },
  savedListTitle: { fontSize: 13, fontWeight: '700', color: '#20242d' },
  savedListCount: { marginLeft: 'auto', fontSize: 11, color: '#9299a5' },
  detailScreen: { flex: 1, backgroundColor: '#f4f5f7' },
  detailContent: { flex: 1 },
  detailHeader: {
    height: 54,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e6e8eb',
    zIndex: 2,
    elevation: 3,
  },
  detailBackButton: {
    width: 48,
    height: 48,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  detailBack: { fontSize: 31, lineHeight: 35, color: '#202b3d', width: 40 },
  detailTitle: { fontSize: 16, fontWeight: '700', color: '#20242d' },
  detailHeaderSpacer: { width: 48 },
  detailList: { flex: 1 },
  commentsSection: {
    paddingHorizontal: 16,
    paddingVertical: 18,
    backgroundColor: '#fff',
  },
  commentsTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#20242d',
    marginBottom: 14,
  },
  commentsLoading: { marginVertical: 18 },
  commentsHint: { fontSize: 13, color: '#858d99', paddingVertical: 12 },
  commentsError: { color: '#c43e4f', fontSize: 13, paddingVertical: 12 },
  commentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 15,
  },
  commentReply: { marginLeft: 28 },
  commentAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e7e9ed',
  },
  commentAvatarFallback: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#90a9d8',
  },
  commentAvatarText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  commentBody: { flex: 1, marginLeft: 9 },
  commentAuthor: { fontSize: 12, fontWeight: '700', color: '#303641' },
  commentDate: { fontWeight: '400', color: '#98a0ac', fontSize: 10 },
  commentContent: {
    color: '#4a5260',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  commentEditButton: { alignSelf: 'flex-start', paddingVertical: 5 },
  commentEditText: { color: '#355b92', fontSize: 11, fontWeight: '700' },
  commentActions: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  commentActionButton: { alignSelf: 'flex-start', paddingVertical: 5 },
  commentActionText: { color: '#667085', fontSize: 11, fontWeight: '600' },
  commentDeleteText: { color: '#c43e4f', fontSize: 11, fontWeight: '600' },
  commentDeletedText: { color: '#9299a5', fontSize: 13, fontStyle: 'italic' },
  commentEditArea: { marginTop: 5 },
  commentEditInput: {
    minHeight: 56,
    maxHeight: 120,
    borderWidth: 1,
    borderColor: '#dfe3e9',
    borderRadius: 9,
    padding: 9,
    color: '#303641',
    fontSize: 13,
    textAlignVertical: 'top',
  },
  commentEditActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 15,
    marginTop: 8,
  },
  commentEditCancel: { color: '#667085', fontSize: 12 },
  commentEditSaveButton: {
    minWidth: 48,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 17,
    backgroundColor: '#355b92',
  },
  commentComposer: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: '#fff',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#e6e8eb',
  },
  commentReplyNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 7,
  },
  commentReplyNoticeText: { color: '#667085', fontSize: 11 },
  commentReplyCancel: { color: '#355b92', fontSize: 11, fontWeight: '600' },
  commentComposerRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 9 },
  commentInput: {
    flex: 1,
    minHeight: 42,
    maxHeight: 110,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 21,
    backgroundColor: '#f2f4f7',
    color: '#303641',
    fontSize: 14,
  },
  commentSubmitButton: {
    minWidth: 55,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 21,
    backgroundColor: '#355b92',
  },
  commentSubmitDisabled: { opacity: 0.45 },
  commentSubmitText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  commentPreviewBlock: {
    marginTop: -9,
    paddingHorizontal: 15,
    paddingBottom: 12,
    backgroundColor: '#fff',
  },
  commentPreviewRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 9,
  },
  commentPreviewAvatar: {
    width: 25,
    height: 25,
    borderRadius: 13,
    backgroundColor: '#e7e9ed',
  },
  commentPreviewFallback: {
    width: 25,
    height: 25,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#90a9d8',
  },
  commentPreviewFallbackText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  commentPreviewBody: { flex: 1, marginLeft: 8 },
  commentPreviewAuthor: { color: '#303641', fontSize: 11, fontWeight: '700' },
  commentPreviewText: {
    color: '#4a5260',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  commentPreviewMore: { alignSelf: 'flex-start', paddingTop: 9 },
  commentPreviewMoreText: { color: '#858d99', fontSize: 12, fontWeight: '600' },
  commentsModalRoot: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(10,15,25,0.42)',
    zIndex: 20,
    elevation: 20,
  },
  commentsModalBackdrop: { ...StyleSheet.absoluteFill },
  commentsModalSheet: {
    height: '82%',
    overflow: 'hidden',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: '#fff',
  },
  commentsModalContent: { flex: 1 },
  commentsModalHeader: {
    height: 54,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e6e8eb',
  },
  commentsModalTitle: { color: '#20242d', fontSize: 15, fontWeight: '700' },
  commentsModalClose: { paddingHorizontal: 8, paddingVertical: 6 },
  commentsModalCloseText: { color: '#667085', fontSize: 12, fontWeight: '600' },
  commentsModalErrorArea: { paddingHorizontal: 18, paddingTop: 10 },
  commentsModalListView: { flex: 1 },
  commentsModalList: { flexGrow: 1, paddingHorizontal: 18, paddingTop: 16 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10 },
  emptyList: { flexGrow: 1, justifyContent: 'center' },
  empty: { textAlign: 'center', color: '#858d99', padding: 20 },
  retry: { color: '#3e72b8', fontWeight: '700' },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  backdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(10,15,25,0.4)',
  },
  sheet: {
    minHeight: 330,
    maxHeight: '90%',
    paddingHorizontal: 20,
    paddingBottom: 28,
    backgroundColor: '#fff',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
  },
  composerHeader: {
    height: 53,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e6e8eb',
  },
  composerBody: { paddingBottom: 8 },
  cancel: { fontSize: 13, color: '#667085' },
  composerTitle: { fontSize: 15, fontWeight: '700', color: '#20242d' },
  share: { fontSize: 13, fontWeight: '700', color: '#3e72b8' },
  input: { height: 145, marginTop: 12, fontSize: 14, color: '#303641' },
  pickers: { flexDirection: 'row', gap: 10, marginTop: 8 },
  picker: {
    flex: 1,
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e3e6eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selected: {
    color: '#3e72b8',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 14,
    marginBottom: 8,
  },
  previewList: { gap: 9, paddingRight: 4 },
  previewCard: {
    width: 104,
    minHeight: 132,
    borderRadius: 11,
    overflow: 'hidden',
    backgroundColor: '#f1f3f6',
    borderWidth: 1,
    borderColor: '#e3e6eb',
  },
  previewImage: { width: '100%', height: 88, backgroundColor: '#e7e9ed' },
  previewVideo: {
    height: 88,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#283449',
  },
  previewPlayGlyph: { fontSize: 26, color: '#fff' },
  previewVideoLabel: { fontSize: 10, color: '#fff', marginTop: 3 },
  orderBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    width: 23,
    height: 23,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#202b3d',
  },
  orderBadgeText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  removeAssetButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(20,25,35,0.72)',
  },
  removeAssetGlyph: { color: '#fff', fontSize: 19, lineHeight: 22 },
  reorderButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 2,
  },
  reorderButton: {
    width: 34,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reorderGlyph: { color: '#355b92', fontSize: 22, lineHeight: 23 },
  disabledGlyph: { color: '#c2c8d0' },
  previewFileName: {
    color: '#707887',
    fontSize: 9,
    paddingHorizontal: 5,
    paddingBottom: 4,
    textAlign: 'center',
  },
  searchScreen: { flex: 1, backgroundColor: '#fff' },
  searchInputWrap: {
    height: 42,
    marginHorizontal: 16,
    marginTop: 13,
    marginBottom: 5,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: '#f1f2f4',
  },
  searchGlyph: { color: '#737b87', fontSize: 21, marginRight: 8 },
  searchInput: { flex: 1, paddingVertical: 0, fontSize: 14, color: '#20242d' },
  searchClear: { color: '#818894', fontSize: 21, paddingHorizontal: 3 },
  searchTabs: {
    height: 45,
    flexDirection: 'row',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e6e8eb',
  },
  searchTab: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  searchTabText: { color: '#7a818c', fontSize: 13, fontWeight: '600' },
  searchTabTextActive: { color: '#202b3d', fontWeight: '700' },
  searchTabIndicator: {
    position: 'absolute',
    bottom: 0,
    width: '42%',
    height: 2,
    backgroundColor: '#202b3d',
  },
  searchPostList: { paddingTop: 8, paddingBottom: 20 },
  searchEmptyList: { flexGrow: 1, justifyContent: 'center', padding: 28 },
  searchEmptyText: { color: '#8b929d', fontSize: 13, textAlign: 'center' },
  searchUserFilters: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  searchUserFilter: {
    paddingHorizontal: 13,
    paddingVertical: 7,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e3e6eb',
    backgroundColor: '#fff',
  },
  searchUserFilterActive: {
    backgroundColor: '#202b3d',
    borderColor: '#202b3d',
  },
  searchUserFilterText: { color: '#667085', fontSize: 11, fontWeight: '600' },
  searchUserFilterTextActive: { color: '#fff' },
  searchUserList: { paddingHorizontal: 16, paddingBottom: 20 },
  searchUserIdentity: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchUserRow: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#eceef1',
  },
  searchUserAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#edf0f4',
  },
  searchUserAvatarFallback: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#dfe6f0',
  },
  searchUserAvatarText: { color: '#40536f', fontSize: 16, fontWeight: '700' },
  searchUserDetails: { flex: 1, marginLeft: 11, marginRight: 8 },
  searchUserName: { color: '#20242d', fontSize: 13, fontWeight: '700' },
  searchUserId: { color: '#858c97', fontSize: 11, marginTop: 4 },
  searchFollowButton: {
    minWidth: 76,
    height: 31,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderRadius: 7,
    backgroundColor: '#202b3d',
  },
  searchFollowingButton: { backgroundColor: '#f0f1f3' },
  searchFollowButtonText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  searchFollowingButtonText: { color: '#3f4650' },
  profileFollowButton: {
    minWidth: 74,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 7,
    backgroundColor: '#202b3d',
  },
  profileFollowingButton: { backgroundColor: '#eef0f3' },
  profileFollowText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  profileFollowingText: { color: '#3f4650' },
  notice: {
    fontSize: 11,
    color: '#98a0ac',
    textAlign: 'center',
    marginTop: 15,
  },
});

export default styles;
